server:
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: board
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml
 